version: '3'

services:
  www:
    build: ./init/apache
    container_name: phpalways_app
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    environment:
      USE_DB: 1
      MYSQL_HOST: db
      MYSQL_USER: admin
      MYSQL_PASS: password
      MYSQL_DB: phpalways
      PWD_SALT: dddd18766b286daf538dd7cf774d0e22
    links:
      - db

  db:
    image: mariadb:latest
    restart: always
    container_name: phpalways_db
    volumes:
      - ./init/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=phpalways
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8 
      - --collation-server=utf8_general_ci